export const envSchema = {
  type: "object",
  properties: {
    HOSTNAME: { type: "string", minLength: 2 },
    PORT: { type: "string", pattern: "^[0-9]+$" },
    NODE_ENV: { type: "string", enum: ["development", "production", "test"] },
    ADMIN_API_KEY: { type: "string", minLength: 8 },
    CORS_ORIGIN: { type: "string", minLength: 1 },
    GITHUB_TOKEN: { type: "string" },
    SESSION_SECRET: { type: "string", minLength: 16 },
    MYSQL_HOST: { type: "string", minLength: 1 },
    MYSQL_PORT: { type: "string", pattern: "^[0-9]+$" },
    MYSQL_USER: { type: "string", minLength: 1 },
    MYSQL_PASSWORD: { type: "string" },
    MYSQL_DB: { type: "string", minLength: 1 },
    REDIS_HOST: { type: "string", minLength: 1 },
    REDIS_PORT: { type: "string", pattern: "^[0-9]+$" },
  },
  required: [
    "HOSTNAME",
    "PORT",
    "NODE_ENV",
    "ADMIN_API_KEY",
    "SESSION_SECRET",
    "MYSQL_HOST",
    "MYSQL_PORT",
    "MYSQL_USER",
    "MYSQL_PASSWORD",
    "MYSQL_DB",
    "REDIS_HOST",
    "REDIS_PORT",
  ],
  additionalProperties: false,
};
